MLE-14323 Bug fix for joining cluster

diff --git a/charts/templates/configmap-scripts.yaml b/charts/templates/configmap-scripts.yaml
--- a/charts/templates/configmap-scripts.yaml
+++ b/charts/templates/configmap-scripts.yaml
@@ -10,6 +10,7 @@ metadata:
 data:
   liveness-probe.sh: |
     #!/bin/bash
+    pid=$(pgrep -fn start.marklogic)
     log () {
       local TIMESTAMP=$(date +"%Y-%m-%d %T.%3N")
       # Check to make sure pod doesn't terminate if PID value is empty for any reason
@@ -17,8 +18,6 @@ data:
           echo "${TIMESTAMP} $@" > /proc/$pid/fd/1
       fi
     }
-    
-    pid=$(pgrep start.marklogic)
 
     # Check if ML service is running. Exit with 1 if it is other than running
     ml_status=$(/etc/init.d/MarkLogic status)
@@ -115,6 +114,8 @@ data:
     MARKLOGIC_ADMIN_USERNAME="$(< /run/secrets/ml-secrets/username)"
     MARKLOGIC_ADMIN_PASSWORD="$(< /run/secrets/ml-secrets/password)"
 
+    pid=$(pgrep -fn start.marklogic)
+
     log () {
         local TIMESTAMP=$(date +"%Y-%m-%d %T.%3N")
         # Check to make sure pod doesn't terminate if PID value is empty for any reason
@@ -124,7 +125,6 @@ data:
         fi
     }
 
-    pid=$(pgrep start.marklogic)
     log "Info: [prestop] Prestop Hook Execution"
 
     my_host=$(hostname -f)
@@ -192,7 +192,7 @@ data:
     MARKLOGIC_ADMIN_USERNAME="$(< /run/secrets/ml-secrets/username)"
     MARKLOGIC_ADMIN_PASSWORD="$(< /run/secrets/ml-secrets/password)"
 
-    pid=$(pgrep start.marklogic)
+    pid=$(pgrep -fn start.marklogic)
 
     ###############################################################
     # Logging utility
@@ -221,6 +221,8 @@ data:
         
         echo $message >> /tmp/script.log
     }
+
+    info "PID: $pid"
 
     ################################################################
     # restart_check(hostname, baseline_timestamp)
@@ -470,52 +472,61 @@ data:
     ################################################################
     function join_cluster {
         hostname=$1
+        retry_count=5
 
-        # check if Bootstrap Host is ready
-        # if server could not be reached, response_code == 000
-        # if host has not join cluster, return 404
-        # if bootstrap host not init, return 403
-        # if Security DB not set or credential not correct return 401
-        # if host is already in cluster, return 200
-        response_code=$( curl -s --anyauth -o /dev/null -w '%{http_code}' \
-            --user "${MARKLOGIC_ADMIN_USERNAME}":"${MARKLOGIC_ADMIN_PASSWORD}" $HTTPS_OPTION \
-            $HTTP_PROTOCOL://${MARKLOGIC_BOOTSTRAP_HOST}:8002/manage/v2/hosts/${hostname}/properties?format=xml \
-        )
+        while [ $retry_count -gt 0 ]; do
+            # check if host is already in the cluster
+            # if server could not be reached, response_code == 000
+            # if host has not join cluster, return 404
+            # if bootstrap host not init, return 403
+            # if Security DB not set or credential not correct return 401
+            # if host is already in cluster, return 200
+            response_code=$(curl -s --anyauth -o /dev/null -w '%{http_code}' \
+                --user "${MARKLOGIC_ADMIN_USERNAME}":"${MARKLOGIC_ADMIN_PASSWORD}" $HTTPS_OPTION \
+                $HTTP_PROTOCOL://${MARKLOGIC_BOOTSTRAP_HOST}:8002/manage/v2/hosts/${hostname}/properties?format=xml \
+            )
 
-        info "response_code: $response_code"
+            if [ "${response_code}" = "200" ]; then
+                info "host has already joined the cluster"
+                return 0
+            elif [ "${response_code}" = "401" ]; then
+                error "Failed to join the cluster: Security DB not set or credential not correct. Exit."
+                return 1
+            elif [ "${response_code}" != "404" ]; then
+                info "Response code from bootstrap host: ${response_code}. Retry again in 10s"
+                sleep 10s
+                ((retry_times--))
+                if [ $retry_times -le 0 ]; then
+                    error "Failed to get the expected response form bootstrap host after 5 times retry. Exit."
+                    return 1
+                fi
+            else
+                info "Proceed to joining bootstrap host"
+                break
+            fi
+        done
 
-        if [ "${response_code}" = "200" ]; then
-            info "host has already joined the cluster"
-            return 0
-        elif [ "${response_code}" != "404" ]; then
-            sleep 10s
-            join_cluster $hostname
-        else
-            info "Proceed to joining bootstrap host"
-        fi
-        
         # process to join the host
-
         # Wait until the group is ready
-        retry_count=10
+        retry_count=5
         while [ $retry_count -gt 0 ]; do
             GROUP_RESP_CODE=$( curl --anyauth -m 20 -s -o /dev/null -w "%{http_code}" $HTTPS_OPTION -X GET $HTTP_PROTOCOL://${MARKLOGIC_BOOTSTRAP_HOST}:8002/manage/v2/groups/${MARKLOGIC_GROUP} --anyauth --user ${MARKLOGIC_ADMIN_USERNAME}:${MARKLOGIC_ADMIN_PASSWORD} )
+            info "GROUP_RESP_CODE: $GROUP_RESP_CODE"
             if [[ ${GROUP_RESP_CODE} -eq 200 ]]; then
                 info "Found the group, process to join the group"
                 break
             else 
-                ((retry_count--))
                 info "GROUP_RESP_CODE: $GROUP_RESP_CODE , retry $retry_count times to joining ${MARKLOGIC_GROUP} group in marklogic cluster"
                 sleep 10s
+                ((retry_count--))
+                if [[ $retry_count -le 0 ]]; then
+                    info "retry_count: $retry_count"
+                    error "pass timeout to wait for the group ready"
+                    exit 1
+                fi
             fi
         done
 
-        if [[ $retry_count -le 0 ]]; then
-            info "retry_count: $retry_count"
-            error "pass timeout to wait for the group ready"
-            exit 1
-        fi
-        
         info "${hostname} - joining cluster of group ${MARKLOGIC_GROUP}"
         payload=\"group=${MARKLOGIC_GROUP}\"
         curl_retry_validate "http://${hostname}:8001/admin/v1/server-config" 200 \
@@ -538,7 +549,7 @@ data:
         
         # 202 causes restart
         info "${hostname} - restart triggered"
-        # restart_check "${hostname}" "${timestamp}"
+        restart_check "${hostname}" "${timestamp}"
 
         info "${hostname} - joined group ${MARKLOGIC_GROUP}"
     }
