MLE-13136: Merging release/1.1.1 to master (#205)
* MLE-11843 fix HC tests (#189)

* update pod name for the tests

* update pod name for the tests in makefile

* increment docker version to the latest release

* MLE-12244: fixes for failing upgrade tests on jenkins (#190)

* MLE-12574: Warning message changes commit while using ML rootless image (#197)

Co-authored-by: sumanthravipati <sumanth.ravipati@progress.com>

* MLE-4146: Liveness and Readiness Probe Changes Commit (#198)

* add dependent image scanning (#199)

* MLE-12746: big fix for helm upgrade not working for TLS configuration

* Updating chart version in chart.yaml (#204)

* add TLS enable check

---------

Co-authored-by: Vitaly <korolev@progress.com>
Co-authored-by: Peng Zhou <27710236+pengzhouml@users.noreply.github.com>
Co-authored-by: sumanthravipati <43222215+sumanthravipati@users.noreply.github.com>
Co-authored-by: sumanthravipati <sumanth.ravipati@progress.com>
Co-authored-by: Peng Zhou <peng.zhou@progress.com>
Co-authored-by: Romain Winieski <winieski@progress.com>

diff --git a/charts/templates/statefulset.yaml b/charts/templates/statefulset.yaml
--- a/charts/templates/statefulset.yaml
+++ b/charts/templates/statefulset.yaml
@@ -224,7 +224,9 @@ spec:
             {{- if .Values.hugepages.enabled }}
             - name: huge-pages
               mountPath: {{ .Values.hugepages.mountPath }}
-            {{- end }}            
+            {{- end }} 
+            - name: scripts
+              mountPath: /tmp/scripts           
           env:
             - name: MARKLOGIC_ADMIN_USERNAME_FILE
               value: "ml-secrets/username"
@@ -313,41 +315,40 @@ spec:
                     # Begin Group Configuration
                     if [[ $POD_NAME == *-0 ]] && [[ $MARKLOGIC_CLUSTER_TYPE == "bootstrap" ]]; then
                       [ -f /var/opt/MarkLogic/group_cfg ] && current_group_cfg=$(cat /var/opt/MarkLogic/group_cfg)
-                      if [ "${MARKLOGIC_GROUP}:${XDQP_SSL_ENABLED}" = "${current_group_cfg}" ]; then
-                          log "Info: [poststart] Group config has not changed, poststart hook complete"
-                          exit 0
-                      fi
+                      if [ "${MARKLOGIC_GROUP}:${XDQP_SSL_ENABLED}:${MARKLOGIC_JOIN_TLS_ENABLED}" = "${current_group_cfg}" ]; then
+                        log "Info: [poststart] Group config has not changed, complete group configuration"
+                      else 
+                        log "Info: [poststart] Begin group configuration."
+                        while [ ! -f /var/opt/MarkLogic/ready ]; do
+                          log "[poststart] waiting for MarkLogic server to be ready"
+                          sleep 5s
+                        done
 
-                      log "Info: [poststart] Begin group configuration."
-                      while [ ! -f /var/opt/MarkLogic/ready ]; do
-                        log "[poststart] waiting for MarkLogic server to be ready"
-                        sleep 5s
-                      done
+                        GROUP_CFG_TEMPLATE='{"group-name":"%s", "xdqp-ssl-enabled":"%s"}'
+                        GROUP_CFG=$(printf "$GROUP_CFG_TEMPLATE" "$MARKLOGIC_GROUP" "$XDQP_SSL_ENABLED")
 
-                      GROUP_CFG_TEMPLATE='{"group-name":"%s", "xdqp-ssl-enabled":"%s"}'
-                      GROUP_CFG=$(printf "$GROUP_CFG_TEMPLATE" "$MARKLOGIC_GROUP" "$XDQP_SSL_ENABLED")
-
-                      log "Info: [poststart] Updating group configuration: ${GROUP_CFG}"
-                      GROUP_RESP_CODE=`curl --retry 5 --retry-max-time 60 -o /tmp/restart_payload.xml -w "%{http_code}" --anyauth -m 20 -s -X PUT -H "Content-type: application/json" -d "${GROUP_CFG}" http://${MARKLOGIC_BOOTSTRAP_HOST}:8002/manage/v2/groups/Default/properties --user ${MARKLOGIC_ADMIN_USERNAME}:${MARKLOGIC_ADMIN_PASSWORD}`
-                    
-                      # check whether MarkLogic has restarted
-                      if [[ ${GROUP_RESP_CODE} -eq 202 ]] || [[ ${GROUP_RESP_CODE} -eq 204 ]]; then
-                        log "Info: [poststart] Successfully configured properties for $MARKLOGIC_GROUP group on the MarkLogic cluster."
-                        TIMESTAMP=$(< /tmp/restart_payload.xml grep "last-startup" | sed 's%^.*<last-startup.*>\(.*\)</last-startup>.*$%\1%')
-                        rm  -f /tmp/restart_payload.xml
-                        if [[ -n ${TIMESTAMP} ]]; then
-                          restart_check ${TIMESTAMP}
-                        fi
-                        if [[ $MARKLOGIC_IMAGE_TYPE == "rootless" ]]; then
-                          sh -c 'echo -n '"${MARKLOGIC_GROUP}:${XDQP_SSL_ENABLED}"' > /var/opt/MarkLogic/group_cfg'
+                        log "Info: [poststart] Updating group configuration: ${GROUP_CFG}"
+                        GROUP_RESP_CODE=`curl --retry 5 --retry-max-time 60 -o /tmp/restart_payload.xml -w "%{http_code}" --anyauth -m 20 -s -X PUT -H "Content-type: application/json" -d "${GROUP_CFG}" http://${MARKLOGIC_BOOTSTRAP_HOST}:8002/manage/v2/groups/Default/properties --user ${MARKLOGIC_ADMIN_USERNAME}:${MARKLOGIC_ADMIN_PASSWORD}`
+                      
+                        # check whether MarkLogic has restarted
+                        if [[ ${GROUP_RESP_CODE} -eq 202 ]] || [[ ${GROUP_RESP_CODE} -eq 204 ]]; then
+                          log "Info: [poststart] Successfully configured properties for $MARKLOGIC_GROUP group on the MarkLogic cluster."
+                          TIMESTAMP=$(< /tmp/restart_payload.xml grep "last-startup" | sed 's%^.*<last-startup.*>\(.*\)</last-startup>.*$%\1%')
+                          rm  -f /tmp/restart_payload.xml
+                          if [[ -n ${TIMESTAMP} ]]; then
+                            restart_check ${TIMESTAMP}
+                          fi
+                          if [[ $MARKLOGIC_IMAGE_TYPE == "rootless" ]]; then
+                            sh -c 'echo -n '"${MARKLOGIC_GROUP}:${XDQP_SSL_ENABLED}:${MARKLOGIC_JOIN_TLS_ENABLED}"' > /var/opt/MarkLogic/group_cfg'
+                          else
+                            sudo sh -c 'echo -n '"${MARKLOGIC_GROUP}:${XDQP_SSL_ENABLED}:${MARKLOGIC_JOIN_TLS_ENABLED}"' > /var/opt/MarkLogic/group_cfg'
+                          fi
+                          log "Info: [poststart] ${GROUP_CFG} saved"
                         else
-                          sudo sh -c 'echo -n '"${MARKLOGIC_GROUP}:${XDQP_SSL_ENABLED}"' > /var/opt/MarkLogic/group_cfg'
+                          log "Error: [poststart] Failed to configure properties for $MARKLOGIC_GROUP group.
+                          log "Error: [poststart] Expected response code 202 or 204, got "${GROUP_RESP_CODE}"
+                          exit 1
                         fi
-                        log "Info: [poststart] ${GROUP_CFG} saved"
-                      else
-                        log "Error: [poststart] Failed to configure properties for $MARKLOGIC_GROUP group.
-                        log "Error: [poststart] Expected response code 202 or 204, got "${GROUP_RESP_CODE}"
-                        exit 1
                       fi
                     else
                       log "Info: [poststart] This is not bootstrap host. Skipping group configuration."
@@ -576,9 +577,10 @@ spec:
           {{- end }}
           {{- if .Values.livenessProbe.enabled }}
           livenessProbe:
-            httpGet:
-              path: /
-              port: health-check
+            exec:
+              command:
+                - /bin/bash
+                - /tmp/scripts/liveness-probe.sh
             initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
             periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
             timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
@@ -595,17 +597,6 @@ spec:
             timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
             failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
             successThreshold: {{ .Values.readinessProbe.successThreshold }}
-          {{- end }}
-          {{- if .Values.startupProbe.enabled }}
-          startupProbe:
-            exec:
-              command:
-                - ls
-                - /var/opt/MarkLogic/ready
-            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
-            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
-            successThreshold: {{ .Values.startupProbe.successThreshold }}
-            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
           {{- end }}
           {{- with .Values.resources }}
           resources: {{- toYaml . | nindent 12 }}
@@ -666,6 +657,10 @@ spec:
         - name: mladmin-secrets
           secret:
             secretName: {{ include "marklogic.authSecretNameToMount" . }}
+        - name: scripts
+          configMap:
+            name: {{ .Release.Name }}-scripts
+            defaultMode: 0755
         {{- if .Values.logCollection.enabled }}
         - name: {{ include "marklogic.fullname" . }}-fb-config-map
           configMap:
