fixed exit conditions and added retry logic for configure group

diff --git a/charts/templates/statefulset.yaml b/charts/templates/statefulset.yaml
--- a/charts/templates/statefulset.yaml
+++ b/charts/templates/statefulset.yaml
@@ -33,27 +33,36 @@ spec:
                       local TIMESTAMP=$(date +"%Y-%m-%d %T.%3N")
                       echo "${TIMESTAMP}  $@"
                     }
-            log "Info: [initContainer] Begin init container configure-group execution"
+            log "Info: [initContainer] Begin configure-group execution"
             if [[ $POD_NAME != *-0 ]]; then
               log "Info: [initContainer] Skipping creation of group $MARKLOGIC_GROUP as $POD_NAME is not the first node in the group."
-            else
-              HOST_RESP_CODE=`curl --anyauth -m 20 -s -o /dev/null -w "%{http_code}" -X GET http://${MARKLOGIC_BOOTSTRAP_HOST}:8002/manage/v2/hosts --anyauth --user ${MARKLOGIC_ADMIN_USERNAME}:${MARKLOGIC_ADMIN_PASSWORD}`
-              if [[ ${HOST_RESP_CODE} -ne 200 ]]; then
-                log "Error: [initContainer] Bootstrap host $MARKLOGIC_BOOTSTRAP_HOST not found."
-              else
-                GROUP_CFG_TEMPLATE='{"group-name":"%s"}'
-                GROUP_CFG=$(printf "$GROUP_CFG_TEMPLATE" "$MARKLOGIC_GROUP")
-                GROUP_RESP_CODE=`curl --anyauth -m 20 -s -o /dev/null -w "%{http_code}" -X GET http://${MARKLOGIC_BOOTSTRAP_HOST}:8002/manage/v2/groups/${MARKLOGIC_GROUP} --anyauth --user ${MARKLOGIC_ADMIN_USERNAME}:${MARKLOGIC_ADMIN_PASSWORD}`
-
-                if [[ ${GROUP_RESP_CODE} -eq 200 ]]; then
-                  log "Info: [initContainer] Skipping creation of group $MARKLOGIC_GROUP as it already exists on the MarkLogic cluster." 
-                else
-                  log "Info: [initContainer] Group $MARKLOGIC_GROUP does not exist, creating $MARKLOGIC_GROUP on the MarkLogic cluster."
-                  curl --anyauth --user ${MARKLOGIC_ADMIN_USERNAME}:${MARKLOGIC_ADMIN_PASSWORD} -m 20 -s -X POST -d "${GROUP_CFG}" -H "Content-type: application/json" http://${MARKLOGIC_BOOTSTRAP_HOST}:8002/manage/v2/groups
-                fi    
-              fi      
+              exit 0
             fi
-            log "Info: [initContainer] Init container execution completed"
+            HOST_RESP_CODE=`curl --anyauth -m 20 -s -o /dev/null -w "%{http_code}" -X GET http://${MARKLOGIC_BOOTSTRAP_HOST}:8002/manage/v2/hosts --anyauth --user ${MARKLOGIC_ADMIN_USERNAME}:${MARKLOGIC_ADMIN_PASSWORD}`
+            if [[ ${HOST_RESP_CODE} -ne 200 ]]; then
+              log "Error: [initContainer] Bootstrap host $MARKLOGIC_BOOTSTRAP_HOST not found, exiting Init container."
+              exit 1
+            fi
+            GROUP_CFG_TEMPLATE='{"group-name":"%s"}'
+            GROUP_CFG=$(printf "$GROUP_CFG_TEMPLATE" "$MARKLOGIC_GROUP")
+            GROUP_RESP_CODE=`curl --anyauth -m 20 -s -o /dev/null -w "%{http_code}" -X GET http://${MARKLOGIC_BOOTSTRAP_HOST}:8002/manage/v2/groups/${MARKLOGIC_GROUP} --anyauth --user ${MARKLOGIC_ADMIN_USERNAME}:${MARKLOGIC_ADMIN_PASSWORD}`
+            if [[ ${GROUP_RESP_CODE} -eq 200 ]]; then
+              log "Info: [initContainer] Skipping creation of group $MARKLOGIC_GROUP as it already exists on the MarkLogic cluster." 
+              exit 0
+            fi
+            log "Info: [initContainer] Group $MARKLOGIC_GROUP does not exist, configuring group $MARKLOGIC_GROUP on the MarkLogic cluster."
+            for i in $(seq 1 5); do
+              res_code=`curl --anyauth --user ${MARKLOGIC_ADMIN_USERNAME}:${MARKLOGIC_ADMIN_PASSWORD} -m 20 -s -w '%{http_code}' -X POST -d "${GROUP_CFG}" -H "Content-type: application/json" http://${MARKLOGIC_BOOTSTRAP_HOST}:8002/manage/v2/groups`
+              if [[ ${res_code} -eq 201 ]]; then
+                log "Info: [initContainer] Successfully configured group $MARKLOGIC_GROUP on the MarkLogic cluster."
+                break
+              else
+                log "Info: [initContainer] Configure group $MARKLOGIC_GROUP retry attempt $i "
+                log "Info: [initContainer] Expected response code 202, got $res_code"
+                sleep 10s
+              fi
+              [ $i -eq 5 ] && exit 1
+            done
         env: 
         - name: MARKLOGIC_GROUP
           value: {{ .Values.group.name }}
